# Generated by Django 4.2.7 on 2023-11-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEntrega',
            fields=[
                ('documento_entrega_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaTransporte',
            fields=[
                ('guia_transporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField()),
                ('documento_entrega_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.documentoentrega')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('transportista_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='POD',
            fields=[
                ('pod_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('guia_transporte_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.guiatransporte')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('linea_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_entrega_estimada', models.DateField()),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.pedido')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='guiatransporte',
            name='transportista_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.transportista'),
        ),
        migrations.AddField(
            model_name='documentoentrega',
            name='pedido_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firplak_app.pedido'),
        ),
    ]
